### ISSUE TITLE
Crunch failed to build due to error C2664 C2027 C2079 C2737 with MSVC on windows

### ISSUE THREAD

**Issue by spacelg** [dragonmux/crunch#14]
Hi All,

Environment:
VS 2019 + Windows Server 2016

We are using the latest unreleased version of MSVC to test open source projects. Recently we are trying to add crunch to our test suite, but after building, Crunch failed to build due to error C2664 C2027 C2079 C2737 with MSVC on windows. This issue can be reproduced on latest version 12b6530 on main branch. Could you please help look at this issue?

**Repro steps:**
1. git clone https://github.com/DX-MON/crunch F:\gitP\DX-MON\crunch
2. git submodule update --init --recursive
3. Open vs2019 x64 command prompt && cd F:\gitP\DX-MON\crunch
4. set PATH=C:\Python\Python37\;%PATH%
5. set PATH=C:\Python\Python37\Scripts;%PATH%
6. python -m pip install --upgrade pip setuptools wheel
7. pip3 install meson
8. set PATH=F:\tools\depot_tools;%PATH%"
9. meson build
10. cd build
11. ninja

[build.log](https://github.com/DX-MON/crunch/files/7378944/build.log)

Error info:
--- stdout ---
testLogger.cpp
F:/gitP/DX-MON/crunch/substrate\substrate/internal/fd_compat(60): error C2664: 'int _fstat64(int,_stat64 *)': cannot convert argument 2 from 'substrate::internal::stat_t *' to '_stat64 *'
F:/gitP/DX-MON/crunch/substrate\substrate/internal/fd_compat(60): note: Types pointed to are unrelated; conversion requires reinterpret_cast, C-style cast or function-style cast
C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt\sys/stat.h(169): note: see declaration of '_fstat64'
F:/gitP/DX-MON/crunch/substrate\substrate/fd(93): error C2027: use of undefined type 'substrate::internal::_stat64'
F:/gitP/DX-MON/crunch/substrate\substrate/internal/fd_compat(54): note: see declaration of 'substrate::internal::_stat64'
F:/gitP/DX-MON/crunch/substrate\substrate/fd(92): error C2027: use of undefined type 'substrate::internal::_stat64'
F:/gitP/DX-MON/crunch/substrate\substrate/internal/fd_compat(54): note: see declaration of 'substrate::internal::_stat64'
F:/gitP/DX-MON/crunch/substrate\substrate/fd(94): error C2079: 'fileStat' uses undefined struct 'substrate::internal::_stat64'
F:/gitP/DX-MON/crunch/substrate\substrate/fd(95): error C2664: 'int substrate::internal::fstat(int32_t,substrate::internal::stat_t *) noexcept': cannot convert argument 2 from 'int *' to 'substrate::internal::stat_t *'
F:/gitP/DX-MON/crunch/substrate\substrate/fd(95): note: Types pointed to are unrelated; conversion requires reinterpret_cast, C-style cast or function-style cast
F:/gitP/DX-MON/crunch/substrate\substrate/internal/fd_compat(60): note: see declaration of 'substrate::internal::fstat'
F:/gitP/DX-MON/crunch/substrate\substrate/fd(104): error C2079: 'fileStat' uses undefined struct 'substrate::internal::_stat64'
F:/gitP/DX-MON/crunch/substrate\substrate/fd(105): error C2664: 'int substrate::internal::fstat(int32_t,substrate::internal::stat_t *) noexcept': cannot convert argument 2 from 'int *' to 'substrate::internal::stat_t *'
F:/gitP/DX-MON/crunch/substrate\substrate/fd(105): note: Types pointed to are unrelated; conversion requires reinterpret_cast, C-style cast or function-style cast
F:/gitP/DX-MON/crunch/substrate\substrate/internal/fd_compat(60): note: see declaration of 'substrate::internal::fstat'
F:/gitP/DX-MON/crunch/substrate\substrate/fd(105): error C2737: 'result': const object must be initialized

--- stderr ---

[42/42] Generating crunch++-testCrunch++ with a custom command (wrapped by meson to set PATH)
ninja: build stopped: subcommand failed.

**Comment by amyspark** [comment]
Hi @spacelg, this has already been reported to MSVC and we are awaiting the release of a bugfix: [#1547919](https://developercommunity.visualstudio.com/t/crash-on-constexpr-creation-of-a-stdarray-of-const/1547919?from=email).

**Comment by spacelg** [comment]
Hi @DX-MON, thank you for the fix and prompt reply. We've tried the latest commit and updated submodules. It works and can build pass.

But when we try to run test, it fails again as shown below. 

![Capture](https://user-images.githubusercontent.com/42860526/138202823-4df607bd-71c1-47f5-806a-68fc6dbfa7cd.PNG)

Print_run_test.log: 
[Print_run_test.log](https://github.com/DX-MON/crunch/files/7385646/Print_run_test.log)

meson-logs_testlog.log: 
[meson-logs_testlog.log](https://github.com/DX-MON/crunch/files/7385652/meson-logs_testlog.log)

**Comment by spacelg** [comment]
Hi @amyspark, thank you for your info and reminders. We know this MSVC bug#[1547919](https://developercommunity.visualstudio.com/t/crash-on-constexpr-creation-of-a-stdarray-of-const/1547919?from=email). 

This bug has been fixed in the internal version of MSVC, but has not yet been released. We are using the latest internal version of MSVC, so we will not encounter this problem. And now, we've build Crunch pass, but it failed to run test as shown above.

**Comment by amyspark** [comment]
I can confirm that as of MSVC 19.34.31931 (2022 17.4.0 Preview 4.0) this issue cannot be reproduced with either `-Ddefault_library=static` or `-Ddefault_library=shared`, nor it shows on CI, so I'm in favour of closing this bug.

**Comment by dragonmux** [comment]
Apologies that this had slipped an entire year. We agree that as this doesn't repro any more, it can be closed. Thank you for testing, Amy!

Closing as resolved.
